apiVersion: v1
kind: Pod
metadata:
  name: myapp-deployment
  namespace: matfiz
  labels:
    app: myapp
    type: back-end
spec:
  containers:
    - name: sb-demo-java-container
      image: linaiva/sb-demo-java:latest
#      type: ???