spring:
  application:
    name: sb-demo
  datasource:
    url: jdbc:h2:mem:fmfi
  jpa:
    defer-datasource-initialization: true

app:
  hello:
    greeting: Hello
  current-account:
    transaction: 20